### ISSUE TITLE
I use version 0.43,some project in my jenkins works well,can poll text of the url,while some project print Polling error when triggered

### ISSUE THREAD

**Issue by squestc** [jenkinsci/urltrigger-plugin#26]

**Comment by TonyNoble** [comment]
Hi @squestc 

Unfortunately I'm not able to support older versions of the plugin.  Can you update to the latest version and let me know if the issue persists?  If so, could you please also provide examples of the job configuration and the error message?

**Comment by TonyNoble** [comment]
This issue appears to have been superseded by #27 

Closing.
