### ISSUE TITLE
[Improvement]Add a parameter to be injected into the build based on the URL triggger

### ISSUE THREAD

**Issue by rustyscottweber** [jenkinsci/urltrigger-plugin#30]
URL trigger is great, but I wasn't sure where I could post potential improvements or query useful information about how to make the changes myself.

I'd like to inject a variable into the job when a URL trigger triggers a build.  Sort of a, trigger this build with these parameters when this URL changes.  This can be useful if there are more than 1 URL to monitor and the user wishes to change the behavior of their build based on which URL was polled.  It's also useful in general if the build is parameterized and the user wishes to have a parameterized build be triggered by the URL monitor.

Is this something that is possible Via the URL monitor plugin? Do I need to make my own plugin for this?

**Comment by TonyNoble** [comment]
Hi @rustyscottweber 

Potentially, the easiest thing to do would be to propagate the url that triggered the build as an environment variable.  Would that fulfil the requirement?

**Comment by rustyscottweber** [comment]
That could potentially work with a bit of working around and injecting variables into the job in a separate build step.  However, I think the better solution would be to have a "set build parameters" section on the URL trigger dialog so that the URL trigger can build a job which is parameterized without the extra build steps.

**Comment by fyangd** [comment]
I went ahead and opened a PR here for expose this feature: https://github.com/jenkinsci/urltrigger-plugin/commit/57eee206faf16f4684b45f8dda16523e0588ecc0

**Comment by TonyNoble** [comment]
@fyangd - I've merged your PR, but on testing, I'm not sure it actually sets an environment variable.  Can you confirm that you've managed to make this work and how you used the value set?

**Comment by fyangd** [comment]
Hi @TonyNoble, thanks for taking a look.  

I didn't manage to test it E2E in a live Jenkins environment.   I wrote some unit tests [here](https://github.com/fyangd/urltrigger-plugin/blob/866f9d4ebdf2b3992b0c868dd2c9f7a290dcbd80/src/test/java/org/jenkinsci/plugins/urltrigger/environment/URLTriggerEnvironmentContributorTest.java) as confirmation, which I guess wasn't sufficient.

**Comment by TonyNoble** [comment]
Hi @fyangd, I think I've spotted the issue - URLTriggerCause class is never used as a cause for the build, only the values it holds are extracted XTriggerLib and then added to an XTriggerCause object (I'm not sure why it's done this way, it doesn't make a lot of sense).  Your tests assume that a URLTriggerCause object is used and set the job up as such, but that doesn't reflect what happens in a live Jenkins instance.

It looks like some of the XTrigger functionality may need to be overridden to make this work, and to make URLTriggerCause a subclass of XTriggerCause.

**Comment by TonyNoble** [comment]
@rustyscottweber @fyangd - urltrigger-0.49 has now been released, which contains this functionality.  Environment variable URL_TRIGGER_CAUSE will contain the url value that triggered the build.

**Comment by fyangd** [comment]
@TonyNoble, thank you for cleaning up my mess. 😄 

This feature is greatly appreciated, and I'll be using it as soon as possible!

**Comment by rustyscottweber** [comment]
Indeed. I'm actually in the middle of updating my jenkins instance right now. This is good news.
